config/routes.rb
Rails.application.routes.draw do
  root to: 'anxieties#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api, format: 'json' do
    namespace :v1  do
      resources :categories
      resources :anxieties
    end
  end
end

app/models/anxiety.rb
class Anxiety < ApplicationRecord
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  before_validation :delete_whitespace

  validates :name, uniqueness: true, presence: true, null: false

  private
    def delete_whitespace
      self.name = name.strip
    end
end

app/controllers/anxieties_controller.rb
class AnxietiesController < ApplicationController
  before_action :set_anxiety, only: [:show]

  def new
    @ids_and_names_categories = Category.all.pluck(:id, :name)
  end

  def show
  end

  def index
    @anxieties_each_day_hash = Anxiety.order(created_at: "desc").group_by{|a| I18n.l(a.created_at.to_date, format: :long)}
  end

  def create
    @anxiety = Anxiety.new(anxiety_params)
    if @anxiety.save
      redirect_to @anxiety
    else
      render "new"
    end
  end

  private
    def anxiety_params
      params.require(:anxiety).permit(:content, :think, :feeling, :physical, :action, :category_id)
    end

    def set_anxiety
      @anxiety = Anxiety.find_by(id: params[:id])
    end
end

app/controllers/api/v1/anxieties_controller.rb
class Api::V1::AnxietiesController < ApplicationController
  before_action :set_anxiety, only: [:show]

  def show
  end

  def new
    @ids_and_names_categories = Category.all.pluck(:id, :name)
  end

  def index
    @anxieties_each_day_hash = add_day_format_to_array(Anxiety.order(created_at: "desc")).group_by{|a| I18n.l(a[:created_at].to_date, format: :long)}
    render json: {anxieties_each_day: @anxieties_each_day_hash}
  end

  def create
    @anxiety = Anxiety.new(anxiety_params)
    if @anxiety.save
      render json: {anxiety: @anxiety}
    else
      #errorを返す時の処理ってreactだとどうやるんだろう　
      render json: {data: "error"}
    end
  end

  private
    def anxiety_params
      params.require(:anxiety).permit(:content, :thinking, :physical, :action, :category_id)
    end

    def set_anxiety
      @anxiety = Anxiety.find_by(id: params[:id])
    end

    # created_atをいい感じに加えてjsonで返すための準備をするメソッド
    def add_day_format_to_array(anxieties)
      #インスタンス変数を配列に入れ直す+created_atのデータ型変えたやつを返すメソッド
      anxieties_array = []
      anxieties.each do |anxiety|
        anxieties_array.push({
          id: anxiety.id,
          content: anxiety.content,
          thinking: anxiety.thinking,
          physical: anxiety.physical,
          action: anxiety.action,
          created_at: anxiety.created_at,
          updated_at: anxiety.updated_at,
          category_id: anxiety.category_id,
          time_of_created_at: I18n.l(anxiety.created_at, format: :long)
        })
      end
      return anxieties_array
    end

end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController

  # POST /api/v1/categories/new
  def new
    #render json: { status: 'SUCCESS', data: Category.all.pluck(:id, :name) }
    render json: { status: 'SUCCESS', data: Category.all.pluck(:id, :name) }
  end

  # POST /api/v1/categories
  def create
    # なんでparamsでcategoryの中にnameというパラメータが入っているかわからない。後で確認する
    @category = Category.new(category_params)
    if @category.save
      render json: { status: 'SUCCESS', data: @category }
    else
      # reactでのエラー表示どうやってやるのかわからない。後で確認する。
      render json: { status: 'ERROR', data: @category.errors }
    end
  end

  private
    def category_params
      params.permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end
end

app/helpers/anxieties_helper.rb
module AnxietiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/anxieties/index.html.erb
<div class="container">
  <h1>日付ごとの不安一覧</h1>
  <!--<p>日付ごとの不安をチェックして、不安を解決しよう！</p>-->

  <% @anxieties_each_day_hash.each do |key, values| %>
    <div class="card border-dark mb-3">
    <!--  ここに日付を表示する -->
      <h5 class="card-header"><%= key %></h5>
      <ul class="list-group list-group-flush">
        <% values.each do |v| %>
        <!--  ここに不安を表示する -->
          <li class="list-group-item">
            <%= link_to(anxiety_path(v), class: 'list-content') do %>
              <%= v.content %>
              <p class="card-text"><small class="text-muted"><%= I18n.l(v.created_at, format: :long) %></small></p>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/anxieties/new.html.erb
<!-- あとで、react_railsけして、html上でcomoponetを表示できるようにする　-->
<%= react_component("App", {categories: @ids_and_names_categories}) %>

app/views/anxieties/show.html.erb
<p>show page</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnxietyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag  'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <script src="https://kit.fontawesome.com/ad286aedde.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>